/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.magicsweet.sstest;

public class App {

    public static void main(String[] args) {
        System.out.println("i am gay!");
    }
}
